name: kreativeworx
favicon: null
layout_spectrum: 0.5557
typography_spectrum: 0.49729
title: KreativeWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5cc8b'
    - '#bc7731'
    - '#151416'
    - '#9e9da2'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
