name: kreativeworx
favicon: null
layout_spectrum: 0.49309
typography_spectrum: 0.49729
title: KreativeWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8d3d0c'
    - '#fea925'
    - '#8b9198'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
