name: kreativeworx
favicon: null
layout_spectrum: 0.51115
typography_spectrum: 0.49729
title: KreativeWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#515153'
    - '#fefefe'
    - '#929397'
    - '#fa941b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
