name: kreativeworx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4708959865383804
title: KreativeWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#515153'
    - '#fefefe'
    - '#929397'
    - '#fa941b'
  brandStrength: 0.7801372183021158
  lightness: 0.5584020344540477
  saturation: 0.7764059856999665
  rhythmicContrast: 0.27095855050720274
purpose: []
